#!/bin/bash

COLOR_HEX="$(colorpicker --one-shot --preview --short)"

echo $COLOR_HEX | xclip -sel clip

PNG_FILE="/tmp/$(date +%s).png"
convert -size 128x128 xc:$COLOR_HEX $PNG_FILE

notify-send "Color hex copied" "${COLOR_HEX}" --icon="${PNG_FILE}"
