#!/bin/bash

primary_monitor=$(xrandr | awk '/primary/ {print $1;}')
primary_mode="--auto"

secondary_monitor="$(xrandr | awk '/HDMI/ {print $1;}' | sed -n 1p)"
secondary_mode="--auto"
disconnected=$(xrandr | awk "/$secondary_monitor disconnected/")

[ $HOSTNAME == "r4" ] && primary_mode="--mode 1920x1080 --rate 144"
(pgrep -f top-secondary > /dev/null) && kill $(pgrep -f top-secondary)

case "$@" in
	"1")
		xrandr --output $secondary_monitor --off --output $primary_monitor $primary_mode
		;;
	"2")
		if [ ! "$disconnected" ]; then 
			xrandr --output $primary_monitor --off --output $secondary_monitor $secondary_mode
		else
			echo "No monitor connected"
		fi
		;;
	"all")
		if [ ! "$disconnected" ]; then 
			xrandr --output $primary_monitor $primary_mode --output $secondary_monitor $secondary_mode --right-of $primary_monitor
			polybar top-secondary -r &
		else
			echo "No secondary monitor connected"
		fi
		;;
	"clone")
		xrandr --output $primary_monitor $primary_mode --output $secondary_monitor $secondary_mode --same-as $primary_monitor
		;;
	*)
		(xrandr --listactivemonitors | grep -q $secondary_monitor) && monitors 1 || monitors all
		;;
esac
