#!/bin/bash

notify-send 'scrot' 'waiting for selection...'
png_file=$(date +%s).png
maim -s ~/Screenshots/$png_file
xclip -sel clip -t image/png < ~/Screenshots/$png_file
notify-send 'scrot' 'saved to ~/Screenshots'
