#!/bin/bash

systemd-inhibit --what=handle-power-key sleep infinity & 
launch-polybar &
compton -cb &
setxkbmap -layout us,ca -option 'grp:win_space_toggle'
i3-msg "workspace 3; exec google-chrome-stable --force-device-scale-factor=1.2 &"
i3-msg "workspace 10; exec spot &"
i3-msg "workspace 1; exec alacritty &"
autolock &
dunst &
$HOME/.fehbg &	
udiskie &
conky -q &	

disown
