#!/bin/bash

echo Startup i3...

export $(dbus-launch)

# on power button press
systemd-inhibit --what=handle-power-key sleep infinity & 

# keyboard layouts
setxkbmap -layout us,ca -option 'grp:win_space_toggle'

# automount usb
udiskie &

# polybar script
$HOME/Scripts/launch-polybar &

# compositor 
compton -Ccb &

# open apps on startup
i3-msg "workspace 3; exec chromium --force-device-scale-factor=1.2 &"
i3-msg "workspace 1; exec alacritty &"

# background
$HOME/.fehbg &	

# conky stats
conky -c $HOME/.config/conky/.conkyrc 	
conky -c $HOME/.config/conky/.shortcutrc 

# gestures
$HOME/.rbenv/shims/fusuma -c $HOME/.config/fusuma/config.yml &

# Power Management
xfce4-power-manager &

# weather
$HOME/Scripts/weather &

disown
