#!/bin/bash

# on power button press
systemd-inhibit --what=handle-power-key sleep infinity & 

# keyboard layouts
setxkbmap -layout us,ca -option 'grp:win_space_toggle'

# automount usb
udiskie &

disown
