#!/bin/bash

(! pgrep -x "polybar" > /dev/null) && polybar top -r &
/home/alexis/.fehbg &
compton -cb &
setxkbmap -layout us,ca -option 'grp:win_space_toggle'
i3-msg "workspace 3; exec google-chrome-stable --force-device-scale-factor=1.2 &"
i3-msg "workspace 10; exec spot &"
load-layout &
autolock &
dunst &
conky &
disown
